application: yetanotherflashcard
version: 1
runtime: python27
api_version: 1
threadsafe: true

skip_files:
- ^(.*/)?\..*
- ^(.*/)?.+\.ya?ml
- ^(.*/)?#.*#
- ^(.*/)?.*(~|\.(bak|py[co]|csv|sh)|/RCS/.*)
- demo/.*
- icon\.html

libraries:
- name: jinja2
  version: latest

handlers:
- url: /((screenshots/)?[-\w\.]+\.(png|ico|css|js)|robots\.txt|about\.html)
  static_files: \1
  upload: ((screenshots/)?[-\w\.]+\.(png|ico|css|js)|robots\.txt|about\.html)

- url: /(manifest\.webapp)
  static_files: \1
  upload: manifest\.webapp
  mime_type: application/x-web-app-manifest+json

- url: /(|yaf.appcache|manage|create|upload|add|remove|edit|publish)
  secure: always
  script: yetanotherflashcard.app
  login: required

- url: /(sync|reportcspviolation|text.*)
  script: yetanotherflashcard.app
