application: yetanotherflashcard
version: 1
runtime: python27
api_version: 1
threadsafe: true

skip_files:
- ^(.*/)?\..*
- ^(.*/)?.+\.ya?ml
- ^(.*/)?#.*#
- ^(.*/)?.*(~|\.(bak|py[co]|csv|sh)|/RCS/.*)
- demo/.*
- icon\.html

libraries:
- name: jinja2
  version: latest

handlers:
- url: /([-\w\.]+\.(png|ico|css|js)|robots\.txt|manifest\.json)
  static_files: \1
  upload: ([-\w\.]+\.(png|ico|css|js)|robots\.txt|manifest\.json)

- url: /favicon\.ico
  static_files: apple-touch-icon-144x144-precomposed.png
  upload: apple-touch-icon-144x144-precomposed.png

- url: /(|yaf.appcache|create|upload|add|edit|manage|remove)
  secure: always
  script: yetanotherflashcard.app
  login: required

- url: /(sync|reportcspviolation|text.*)
  script: yetanotherflashcard.app
